//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Billing()
        {
            this.PaymentBils = new HashSet<PaymentBil>();
        }
    
        public int Bill_Id { get; set; }
        public int Rid { get; set; }
        public int Did { get; set; }
        public int Pid { get; set; }
        public string Doctor_Name { get; set; }
        public string Patient_Name { get; set; }
        public string Room_Type { get; set; }
        public System.DateTime Bill_Date { get; set; }
        public int Room_Bill { get; set; }
        public int Doctor_Bill { get; set; }
        public int Medicine_Bill { get; set; }
        public int Total_Bill { get; set; }
        public int Aid { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentBil> PaymentBils { get; set; }
    }
}
