//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int Patient_Billid { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public Nullable<int> Room_id { get; set; }
        public Nullable<int> Doctor_id { get; set; }
        public Nullable<int> Assignment_no { get; set; }
        public Nullable<System.DateTime> Bill_Date { get; set; }
        public Nullable<int> Room_Bill { get; set; }
        public Nullable<int> Doctor_Bill { get; set; }
        public Nullable<int> Medicine_Bill { get; set; }
        public Nullable<int> Total_Bill { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Room Room { get; set; }
    }
}
