//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Hospital_Management_SystemEntities2 : DbContext
    {
        public Hospital_Management_SystemEntities2()
            : base("name=Hospital_Management_SystemEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Billing> Billings { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PaymentBil> PaymentBils { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Room_Assignment> Room_Assignment { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
    
        public virtual int DeletePayment(Nullable<int> payment_Id)
        {
            var payment_IdParameter = payment_Id.HasValue ?
                new ObjectParameter("Payment_Id", payment_Id) :
                new ObjectParameter("Payment_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletePayment", payment_IdParameter);
        }
    }
}
