//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_Assignment
    {
        public int Assignment_no { get; set; }
        public Nullable<int> Room_Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public Nullable<System.DateTime> Admission_Date { get; set; }
        public string Doctor_Name { get; set; }
        public string Patient_Condition { get; set; }
        public Nullable<int> Doctor_Id { get; set; }
        public string Patient_Name { get; set; }
        public string Room_Type { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Room Room { get; set; }
    }
}
